version: '3.8'

services:
  backend:
    container_name: task_manager_backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.18.2.106:3306/craques_db
      - SPRING_DATASOURCE_USERNAME=craques_da_bola
      - SPRING_DATASOURCE_PASSWORD=craques
    volumes:
      - ~/.m2:/root/.m2

  frontend:
    container_name: task_manager_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: